services:
  postgres_db:
    image: postgres:16
    container_name: lead_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__USER} -d ${APP_CONFIG__DB__DB}" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data


volumes:
  pgdata:
  redis_data: